Resources:
  KopsAWS:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-4d46d534
      KeyName: KeyKops
      SecurityGroups:
        - !Ref KopsAWSSG
      UserData: !Base64 |
        #!/bin/bash 
        sudo apt-get update -y
        curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
        chmod +x kops-linux-amd64
        sudo mv kops-linux-amd64 /usr/local/bin/kops
        wget https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        sudo mv kubectl /usr/local/bin/
        sudo chmod +x /usr/local/bin/kubectl
        sudo apt install docker.io -y
        sudo chmod 666 /var/run/docker.sock
        sudo apt-get install awscli -y
        sudo apt-get install tmux -y 
  KopsAWSSG:         
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 and HTTP via 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
 
